CREATE TABLE VENDOR
(
  Vendor_Name VARCHAR2(255) NOT NULL,
  Address     VARCHAR2(255) NOT NULL,
  CONSTRAINT Vendor_Name PRIMARY KEY (Vendor_Name)
);

CREATE TABLE DEPARTMENT
(
  Department_Name VARCHAR2(255) NOT NULL,
  Phone           NUMBER        NOT NULL,
  CONSTRAINT Department_Name PRIMARY KEY (Department_Name),
  CONSTRAINT FK_Vendor_Name FOREIGN KEY (Vendor_Name) REFERENCES VENDOR
);

CREATE TABLE EMPLOYEE
(
  EmpNo INTEGER        NOT NULL,
  Name  VARCHAR2(255) NOT NULL,
  Title VARCHAR2(255) NOT NULL,
  DOB   DATE          NOT NULL,
  CONSTRAINT EmpNo PRIMARY KEY (EmpNo),
 CONSTRAINT EMPLOYEE_FK1 FOREIGN KEY(City) REFERENCES LOCATION(City),
  CONSTRAINT EMPLOYEE_FK2 FOREIGN KEY(Department_Name) REFERENCES DEPARTMENT(Department_Name)
);

CREATE TABLE EMP_SKILL
(
  EmpNo            INTEGER       NOT NULL,
  SkillsNo         INTEGER    NOT NULL,
  ProjNo           INTEGER        NOT NULL ,
  CONSTRAINT EMP_SKILL_PK PRIMARY KEY(EmpNo,SkillsNo,ProjNo),
  CONSTRAINT EMP_SKILL_FK1 FOREIGN KEY(EmpNo) REFERENCES EMPLOYEE_T(EmpNo),
  CONSTRAINT EMP_SKILL_FK2 FOREIGN KEY(SkillsNo) REFERENCES SKILLS_T(SkillsNo),
  CONSTRAINT EMP_SKILL_FK3 FOREIGN KEY(ProjNo) REFERENCES PROJECT_T(ProjNo)
);

CREATE TABLE LOCATION
(
  City       VARCHAR2(255) NOT NULL,
  State      VARCHAR2(255) NOT NULL,
  Population NUMBER        NOT NULL,
  CONSTRAINT City PRIMARY KEY (City)
);

CREATE TABLE PROJECT
(
  ProjNo  INTEGER NOT NULL,
  EstCost NUMBER NOT NULL,
  CONSTRAINT ProjNo PRIMARY KEY (ProjNo)
);

CREATE TABLE SKILL
(
  SkillNo     INTEGER        NOT NULL,
  Description VARCHAR2(255) NOT NULL,
  CONSTRAINT SkillNo PRIMARY KEY (SkillNo)
);
